- build.gradle
- compose.yaml
- src/main/java/team/startup/gwangsan/GwangsanApplication.java
- src/main/java/team/startup/gwangsan/domain/member/exception/NotFoundMemberException.java
- src/main/java/team/startup/gwangsan/domain/member/repository/MemberRepository.java
- src/main/java/team/startup/gwangsan/global/auth/MemberDetails.java
- src/main/java/team/startup/gwangsan/global/auth/MemberDetailsService.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorResponse.java
- src/main/java/team/startup/gwangsan/global/exception/GlobalException.java
- src/main/java/team/startup/gwangsan/global/exception/GlobalExceptionHandler.java
- src/main/java/team/startup/gwangsan/global/filter/ExceptionFilter.java
- src/main/java/team/startup/gwangsan/global/filter/JwtAuthenticationFilter.java
- src/main/java/team/startup/gwangsan/global/filter/JwtFilter.java
- src/main/java/team/startup/gwangsan/global/filter/RequestLogFilter.java
- src/main/java/team/startup/gwangsan/global/security/config/JwtSecurityConfig.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- src/main/java/team/startup/gwangsan/global/security/exception/ExpiredTokenException.java
- src/main/java/team/startup/gwangsan/global/security/exception/InvalidMemberPrincipalException.java
- src/main/java/team/startup/gwangsan/global/security/exception/InvalidTokenException.java
- src/main/java/team/startup/gwangsan/global/security/handler/JwtAccessDeniedHandler.java
- src/main/java/team/startup/gwangsan/global/security/handler/JwtAuthenticationEntryPoint.java
- src/main/java/team/startup/gwangsan/global/security/jwt/JwtProperties.java
- src/main/java/team/startup/gwangsan/global/security/jwt/JwtProvider.java
- src/main/java/team/startup/gwangsan/global/security/jwt/TokenParser.java
- src/main/java/team/startup/gwangsan/global/util/MemberUtil.java
- src/main/resources/application.properties
- src/main/resources/application.yml
시큐리티 기본 세팅과 시큐리티 관련 파일들을 수정하였습니다.
Resolves: #4 
- 시큐리티 기본 세팅
> 시큐리티 기본 세팅

- src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
- src/main/java/team/startup/gwangsan/domain/chat/entity/ChatRoom.java
- src/main/java/team/startup/gwangsan/domain/notice/entity/Notice.java
- src/main/java/team/startup/gwangsan/domain/report/entity/Report.java
- src/main/java/team/startup/gwangsan/domain/review/entity/Review.java
> 수정된 ddl에 맞지 않는 엔티티를 수정했습니다
Resolves: #9 
> 엔티티의 `nullable = false` 옵션 제거
> 수정된 ddl에 따라 엔티티 수정

- build.gradle
- src/main/java/team/startup/gwangsan/domain/sms/entity/SmsAuthEntity.java
- src/main/java/team/startup/gwangsan/domain/sms/exception/AuthCodeGenerationException.java
- src/main/java/team/startup/gwangsan/domain/sms/exception/TooManyRequestAuthCodeException.java
- src/main/java/team/startup/gwangsan/domain/sms/presentation/SmsController.java
- src/main/java/team/startup/gwangsan/domain/sms/presentation/dto/SendSmsRequest.java
- src/main/java/team/startup/gwangsan/domain/sms/service/SendSmsService.java
- src/main/java/team/startup/gwangsan/domain/sms/service/impl/SendSmsServiceImpl.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- src/main/java/team/startup/gwangsan/global/sms/SmsConfig.java
- src/main/java/team/startup/gwangsan/global/sms/SmsProperties.java
- src/main/resources/application.yml
회원가입 sms 인증번호 전송 api를 추가하엿습니다.
Resolves: #19 
- coolsms sdk를 이용하여 인증번호 전송 api를 추가하였습니다.
> 회원가입 sms 인증번호 전송

- src/main/java/team/startup/gwangsan/domain/admin/entity/AdminAlert.java
- src/main/java/team/startup/gwangsan/domain/report/entity/Report.java
- src/main/java/team/startup/gwangsan/domain/report/entity/constant/ReportType.java
> report 엔티티의 title 필드를 삭제하고 reportType 필드를 추가하였습니다
Resolves: #24 
> report 엔티티의 title 필드 삭제
> report 엔티티에 reportType 추가
> report 엔티티의 title 필드 삭제 및 reportType 필드 추가

- compose.yaml
- src/main/java/team/startup/gwangsan/domain/sms/entity/SmsAuthEntity.java
- src/main/java/team/startup/gwangsan/domain/sms/exception/AuthCodeGenerationException.java
- src/main/java/team/startup/gwangsan/domain/sms/exception/NotMatchRandomCodeException.java
- src/main/java/team/startup/gwangsan/domain/sms/presentation/SmsController.java
- src/main/java/team/startup/gwangsan/domain/sms/presentation/dto/VerifyCodeRequest.java
- src/main/java/team/startup/gwangsan/domain/sms/service/VerifyCodeService.java
- src/main/java/team/startup/gwangsan/domain/sms/service/impl/VerifyCodeServiceImpl.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- sms 인증번호를 입력하여 올바른지 검사하는 api를 추가하였습니다.
Resolves: #23 
- 인증번호 인증 검사 api 추가
> SMS 인증번호 인증

- src/main/java/team/startup/gwangsan/domain/admin/repository/custom/AdminAlertCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/admin/repository/custom/impl/AdminAlertCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/place/repository/PlaceRepository.java
- src/main/java/team/startup/gwangsan/domain/report/repository/custom/ReportCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/report/repository/custom/impl/ReportCustomRepositoryImpl.java
> 요구사항 변경에 따라 `admin` `FindAlertByAlertTypeAndPlaceService` 로직을 수정했습니다
Resolves: #56 
> FindAlertByAlertTypeAndPlaceService 로직 수정
> admin alert 조회 로직 수정

- src/main/java/team/startup/gwangsan/domain/admin/service/impl/SignInAdminServiceImpl.java
> 어드민 로그인 서비스에 비밀번호 검증 메서드 호출 부분의 주석을 제거했습니다
Resolves: #62 
> `validateMemberPassword` 메서드 주석 해제
> 비밀번호 검증 메서드 주석 해제

- src/main/java/team/startup/gwangsan/domain/auth/presentation/dto/request/SignUpRequest.java
- src/main/java/team/startup/gwangsan/domain/auth/service/impl/SignUpServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
- src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/request/UpdateMyInfoRequest.java
- src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindMyInfoResponse.java
- src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindUserInfoResponse.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindMyInfoServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindUserInfoServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/UpdateMyInfoServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/exception/MemberRelatedKeywordForbiddenException.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/exception/MemberRelatedKeywordNotFoundException.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/RelatedKeywordController.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/dto/response/MyRelatedKeywordResponse.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/dto/response/RelatedKeywordResponse.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/repository/MemberRelatedKeywordRepository.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/DeleteMemberRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/FindMyRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/FindRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/DeleteMemberRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/FindMyRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/FindRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- 회원가입, 내 정보 수정, 조회에 description을 추가하였습니다.
Resolves: #71 
- description 추가
> Description 추가

- src/main/java/team/startup/gwangsan/domain/relatedkeyword/exception/MemberRelatedKeywordForbiddenException.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/exception/MemberRelatedKeywordNotFoundException.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/RelatedKeywordController.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/dto/response/MyRelatedKeywordResponse.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/presentation/dto/response/RelatedKeywordResponse.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/repository/MemberRelatedKeywordRepository.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/DeleteMemberRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/FindMyRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/FindRelatedKeywordService.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/DeleteMemberRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/FindMyRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/relatedkeyword/service/impl/FindRelatedKeywordServiceImpl.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- src/main/java/team/startup/gwangsan/global/filter/JwtAuthenticationFilter.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- Security에서 Authentication관련 설정을 수정하였습니다.
Resolves: #75 
- SecurityConfig에 AuthenticationFilter 추가
- AuthenticationFilter에 /api/auth/**, /api/health 통과시키는 설정 추가
> Security 수정

- src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetReportAlertResponse.java
- src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetSignUpAlertResponse.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/report/repository/custom/impl/ReportCustomRepositoryImpl.java
> `admin` alert 조회 서비스 응답에 placeName 필드를 추가했습니다
Resolves: #79 
> placeName 추가
> admin alert 조회 응답에 placeName 추가

- src/main/java/team/startup/gwangsan/domain/member/repository/MemberDetailRepository.java
- src/main/java/team/startup/gwangsan/domain/post/presentation/PostController.java
- src/main/java/team/startup/gwangsan/domain/post/presentation/dto/response/GetProductMemberResponse.java
- src/main/java/team/startup/gwangsan/domain/post/presentation/dto/response/GetProductResponse.java
- src/main/java/team/startup/gwangsan/domain/post/repository/ProductImageRepository.java
- src/main/java/team/startup/gwangsan/domain/post/repository/ProductRepository.java
- src/main/java/team/startup/gwangsan/domain/post/service/FindProductsByMemberIdService.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByCurrentUserAndTypeAndModeServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByIdServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductsByMemberIdServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductsByTypeAndModeServiceImpl.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
> post 조회 서비스의 응답에 해당 post 주인의 정보를 추가했습니다
Resolves: #87 
> getProductMemberResponse 추가
> post 조회 응답 수정

- src/main/java/team/startup/gwangsan/global/security/jwt/JwtProvider.java
- 엑세스 토큰 만료일을 수정하였습니다.
Resolves: #105 
- accessToken 만료시간을 1일로 변경
> 엑세스 토큰 만료일 수정

- src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindAllUserInfoResponse.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- 전체 사용자 정보 조회 api를 수정하였습니다.
Resolves: #108 
- gwangsan, light 필드 삭제
> 전체 사용자 정보 조회 수정

- src/main/java/team/startup/gwangsan/domain/auth/service/impl/SignUpServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
> 회원가입 시 어드민 알림 생성을 위한 이벤트를 호출하는 코드를 추가하였습니다
Resolves: #110 
> signUpService에 createAdminAlertEvent 호출 코드 추가
> 회원가입 시 어드민 알림 이벤트 호출 코드 추가

- src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/FindProductByIdService.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByIdServiceImpl.java
> 어드민 알림 조회 시 product 조회 관련 오류를 수정했습니다
Resolves: #114 
> 어드민 알림 조회 시 product 조회 관련 오류 수정
> 어드민 알림 조회 시 product 관련 오류 수정

- src/main/resources/application.yml
> 요청의 multipart 파일 크기의 제한을 수정했습니다
Resolves: #123 
> multipart 크기 제한 수정
> 요청 파일 크기 제한 수정

- src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
- src/main/java/team/startup/gwangsan/domain/chat/entity/ChatRoom.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/ChatMessageRepository.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/ChatRoomRepository.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/custom/ChatMessageCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/custom/ChatRoomCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/custom/impl/ChatMessageCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/chat/repository/custom/impl/ChatRoomCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByIdServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
> 엔티티 수정 및 isCompletable의 조건을 수정하였습니다
Resolves: #128 
> 엔티티 수정
> isCompletable 분기문 추가
> 엔티티 수정 및 isCompletable 로직 수정

- src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
> 거래 완료 시 채팅 검증 로직을 주석처리하였습니다
Resolves: #{이슈번호}
> 거래 완료 시 채팅 검증 로직 주석 처리
> 채팅 검증 주석 처리

- src/main/java/team/startup/gwangsan/domain/notice/service/impl/CreateNoticeServiceImpl.java
> notice 생성 서비스 클래스에서 nullPointerException을 해결하였습니다
Resolves: #{이슈번호}
> NullPointerException 해결
> nullPointerException 해결

- src/main/java/team/startup/gwangsan/domain/alert/presentation/dto/response/GetAlertResponse.java
- src/main/java/team/startup/gwangsan/domain/alert/service/impl/FindAlertByCurrentServiceImpl.java
> 앱 알림 조회 응답에 sendMemberId 필드를 추가하였습니다
Resolves: #140 
> GetAlertResponse dto에 sendMemberId 필드 추가
> 앱 알림 조회 응답에 sendMemberId 필드 추가

- src/main/java/team/startup/gwangsan/domain/alert/presentation/dto/response/GetAlertResponse.java
- src/main/java/team/startup/gwangsan/domain/alert/service/impl/FindAlertByCurrentServiceImpl.java
> 앱 알림 조회 응답 dto에 sourceId 필드를 추가하였습니다
Resolves: #143 
> GetAlertResponse dto 수정
> 앱 알림 조회 응답에 sourceId 필드 추가

- src/main/java/team/startup/gwangsan/domain/admin/presentation/AdminController.java
- src/main/java/team/startup/gwangsan/domain/admin/repository/AdminAlertRepository.java
- src/main/java/team/startup/gwangsan/domain/admin/service/RejectAdminAlertService.java
- src/main/java/team/startup/gwangsan/domain/admin/service/VerificationSignUpService.java
- src/main/java/team/startup/gwangsan/domain/admin/service/WithDrawnMemberService.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/RejectAdminAlertServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberRoleServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberStatusServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/VerificationSignUpServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/WithDrawnMemberServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
- src/main/java/team/startup/gwangsan/domain/suspend/presentation/SuspendController.java
- src/main/java/team/startup/gwangsan/domain/suspend/presentation/dto/request/SuspendMemberRequest.java
- src/main/java/team/startup/gwangsan/domain/suspend/repository/SuspendRepository.java
- src/main/java/team/startup/gwangsan/domain/suspend/service/SuspendMemberService.java
- src/main/java/team/startup/gwangsan/domain/suspend/service/impl/SuspendMemberServiceImpl.java
- src/main/java/team/startup/gwangsan/global/scheduler/SuspendReleaseScheduler.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
> 사용자 정지 api 및 어드민 도메인의 api를 추가하였습니다
Resolves: #99 
> 사용자 정지 api 추가
> 어드민 도메인 누락된 api 추가
> 사용자 정지 api 및 어드민 도메인 api 추가

- src/main/java/team/startup/gwangsan/domain/admin/presentation/AdminController.java
- src/main/java/team/startup/gwangsan/domain/admin/service/DeleteAdminAlertService.java
- src/main/java/team/startup/gwangsan/domain/admin/service/impl/DeleteAdminAlertServiceImpl.java
> 어드민 알림 삭제 api를 추가하였습니다
Resolves: #150 
> 어드민 알림 삭제 api 추가
> 어드민 알림 삭제 api 추가

- src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertServiceImpl.java
> 앱 알림 조회 시 잘못된 sourceId를 수정하였습니다
Resolves: #148 
> otherMemberTradeComplete 생성 로직 수정
> 앱 알림 조회 시 잘못된 sourceId 수정

- src/main/java/team/startup/gwangsan/domain/member/repository/MemberDetailRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
- 전체 멤버 정보를 조회할때 발생하는 n+1문제를 해결하였습니다.
Resolves: #156 
- fetch join으로 미리로딩하여 n+1문제 해결
> 전체 멤버 정보 조회 수정

- src/main/java/team/startup/gwangsan/domain/admin/service/impl/VerificationSignUpServiceImpl.java
- 회원가입을 어드민이 수락할 시 5000광산을 지급하는 로직을 추가하였습니다.
Resolves: #158 
- memberDetail에 plusGwangsan메서드를 사용하여 5000광산 지급하는 로직 추가
> 회원가입 수락 시 5000광산 지급 로직 추가

- src/main/java/team/startup/gwangsan/domain/notice/exception/UnauthorizedNoticeAccessException.java
- src/main/java/team/startup/gwangsan/domain/notice/repository/NoticeImageRepository.java
- src/main/java/team/startup/gwangsan/domain/notice/service/impl/DeleteNoticeServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/notice/service/impl/UpdateNoticeServiceImpl.java
- src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
- 공지 수정과 삭제 부분에 수정할 부분이 잇어서 수정하였습니다.
Resolves: #164 
- noticeImage삭제 로직추가
- 본인만 수정 가능하도록 UnauthorizedNoticeAccessException 추가
> 공지 수정, 삭제 수정

- src/main/java/team/startup/gwangsan/domain/member/peresentation/MemberController.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/member/service/FindAllUserInfoService.java
- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
> 전체 사용자 조회 api에 필터 기능을 추가하였습니다
Resolves: #168 
> 전체 사용자 조회 api 필터 기능 추가
> 전체 사용자 조회 api 필터 기능 추가

- src/main/java/team/startup/gwangsan/global/thirdparty/firebase/FcmAdapter.java
> FcmAdapter 클래스에 로깅 관련 코드를 추가하겠습니다
Resolves: #192 
> FcmAdapter에 log 추가
> FcmAdapter 로깅 코드 추가

- .gitignore
- src/main/java/team/startup/gwangsan/domain/chat/presentation/dto/GetChatProductDto.java
- src/main/java/team/startup/gwangsan/domain/chat/service/impl/FindChatMessageByRoomIdServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
- src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
- src/main/java/team/startup/gwangsan/domain/post/presentation/dto/request/CreateProductRequest.java
- src/main/java/team/startup/gwangsan/domain/post/presentation/dto/request/PatchProductRequest.java
- src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
> 광산 거래 로직을 추가하고, 게시글 작성 시 imageIds가 빈 배열로 올 수 있는 버그를 수정했습니다
Resolves: #206 
> 광산 거래 로직 추가
> imageIds 빈 배열로 못오게 수정
> 광산 거래 로직 추가

- src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
- headAdmin은 전체 멤버를 조회할 수 있도록 수정하엿습니다.
Resolves: #213 
- FindAllUserInfoServiceImpl 로직 수정
> headAdmin 조건 수정

- src/main/java/team/startup/gwangsan/domain/auth/presentation/AuthController.java
- src/main/java/team/startup/gwangsan/domain/auth/presentation/dto/request/ResetPasswordRequest.java
- src/main/java/team/startup/gwangsan/domain/auth/service/ResetPasswordService.java
- src/main/java/team/startup/gwangsan/domain/auth/service/impl/ResetPasswordServiceImpl.java
- src/main/java/team/startup/gwangsan/domain/member/entity/Member.java
- src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
- 비밀번호 재설정 API를 추가하였습니다.
Resolves: #218 
- ResetPassword api 추가
> 비밀번호 재설정 API 추가
